import manual_test_plot_setup
import manual_test_plot_event
import manual_test_plot_procedure
import manual_test_calculate_dose_interactive
import manual_test_calculate_dose_static


print("all modes executed")
