COLOR_AZURE_DARK = "#201f1e"
COLOR_BEAM = "red"
COLOR_DETECTOR = "#D3D3D3"
COLOR_PAD = "slateblue"
COLOR_PATIENT = "#CE967C"
COLOR_PLOT_TEXT = "white"
COLOR_SOURCE = "#D3D3D3"
COLOR_TABLE = "#D3D3D3"
COLOR_ZERO_LINE = "limegreen"

COLOR_WIRE_FRAME_BEAM = 'red'
COLOR_WIRE_FRAME_DETECTOR = 'darkslategray'
COLOR_WIRE_FRAME_PAD = '#3f3f3f'
COLOR_WIRE_FRAME_TABLE = '#3f3f3f'

DATA_DS_IRP = "DSIRP"

DIMENSION_PLANE_LENGTH = "plane_length"
DIMENSION_PLANE_RESOLUTION = "plane_resolution"
DIMENSION_PLANE_WIDTH = "plane_width"

IRRADIATION_EVENT_PROCEDURE_KEY_BEAM = "Beam"
IRRADIATION_EVENT_PROCEDURE_KEY_DETECTORS = "Detectors"
IRRADIATION_EVENT_PROCEDURE_KEY_PAD = "Pad"
IRRADIATION_EVENT_PROCEDURE_KEY_PATIENT = "Patient"
IRRADIATION_EVENT_PROCEDURE_KEY_SOURCE = "Source"
IRRADIATION_EVENT_PROCEDURE_KEY_TABLE = "Table"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_BEAM = "WF Beam"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_DETECTORS = "WF Detectors"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_PAD = "WF Pad"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_TABLE = "WF Table"
IRRADIATION_EVENT_STEP_KEY_ARGUMENTS = "args"
IRRADIATION_EVENT_STEP_KEY_LABEL = "label"
IRRADIATION_EVENT_STEP_KEY_METHOD = "method"

MAXIMUM_NUMBER_OF_EVENTS_FOR_INCLUDING_PHANTOM_IN_EVENT_PLOT = 200  # Set to avoid memory errors

MESH_NAME_PAD = "Support pad"
MESH_OPACITY_BEAM = 1.0  # Plotly cannot handle opacity less than 1 at the moment

MODE_CALCULATE_DOSE = "calculate_dose"
MODE_PLOT_EVENT = "plot_event"
MODE_PLOT_PROCEDURE = "plot_procedure"
MODE_PLOT_SETUP = "plot_setup"

OUTPUT_KEY_CORRECTION_BACK_SCATTER = "k_bs"
OUTPUT_KEY_CORRECTION_INVERSE_SQUARE_LAW = "k_isq"
OUTPUT_KEY_CORRECTION_MEDIUM = "k_med"
OUTPUT_KEY_CORRECTION_TABLE = "k_tab"
OUTPUT_KEY_DOSE_MAP = "dose_map"
OUTPUT_KEY_HITS = "hits"
OUTPUT_KEY_KERMA = "kerma"

PHANTOM_MESH_ADULT_MALE = "hudfrid"

PHANTOM_MODEL_CYLINDER = "cylinder"
PHANTOM_MODEL_HUMAN = "human"
PHANTOM_MODEL_PAD = "pad"
PHANTOM_MODEL_PLANE = "plane"
PHANTOM_HUMAN_MESH_SPARSE_MODEL_ENDING = "_reduced_1000t"
PHANTOM_MODEL_TABLE = "table"

PLOT_AXIS_TITLE_X = "X - LON [cm]"
PLOT_AXIS_TITLE_Y = "Y - VER [cm]"
PLOT_AXIS_TITLE_Z = "Z - LAT [cm]"
PLOT_FONT_FAMILY = "Franklin Gothic"
PLOT_HOVER_LABEL_FONT_FAMILY = "Consolas, monospace"
PLOT_SLIDER_BACKGROUND_COLOR = "red"
PLOT_SLIDER_BORDER_COLOR = "rgb(45,45,45)"
PLOT_SLIDER_BORDER_WIDTH = 3
PLOT_SLIDER_FONT_SIZE_CURRENT = 30
PLOT_SLIDER_FONT_SIZE_GENERAL = 16
PLOT_SLIDER_PADDING = dict(b=10, t=10, l=250, r=250)
PLOT_SLIDER_TICK_COLOR = "white"
PLOT_SLIDER_TRANSITION = dict(duration=300, easing="quad-in-out")
PLOT_TITLE_FONT_FAMILY = PLOT_FONT_FAMILY
PLOT_TITLE_FONT_SIZE = 35

RESOLUTION_SPARSE = "sparse"

TABULATED_FIELD_SIDE_LENGTHS_IN_CM = [5, 10, 20, 25, 35]

VISUAL_OFFSET_PHANTOM_MODEL_PLANE = -0.01  # Offset needed to show plane phantom correctly
