COLOR_CANVAS_DARK = 'rgb(52, 49, 49)'
COLOR_CANVAS_LIGHT = 'rgb(252, 252, 252)'
COLOR_PLOT_TEXT_LIGHT = 'rgb(52, 49, 49)'
COLOR_PLOT_TEXT_DARK = 'rgb(252, 252, 252)'
COLOR_ZERO_LINE_LIGHT = "green"
COLOR_ZERO_LINE_DARK = "limegreen"
COLOR_BEAM = "red"
COLOR_DETECTOR = "#D3D3D3"
COLOR_PAD = "slateblue"
COLOR_PATIENT = "#CE967C"
COLOR_SOURCE = "#D3D3D3"
COLOR_TABLE = "#D3D3D3"
COLOR_SLIDER_BACKGROUND = "red"
COLOR_SLIDER_BORDER_LIGHT = "rgb(252,252,252)"
COLOR_SLIDER_BORDER_DARK = "rgb(45,45,45)"
COLOR_SLIDER_TICK_LIGHT = "rgb(52, 49, 49)"
COLOR_SLIDER_TICK_DARK = "white"
COLOR_GRID_DARK = 'rgb(128,128,128)'
COLOR_GRID_LIGHT = 'rgb(160,160,160)'
COLOR_CANVAS_JUPYTERLAB_DARK = 'rgb(33,33,33)'
COLOR_CANVAS_JUPYTERLAB_LIGHT = 'rgb(245,245,245)'

COLOR_WIRE_FRAME_BEAM = 'red'
COLOR_WIRE_FRAME_DETECTOR = 'darkslategray'
COLOR_WIRE_FRAME_PAD = '#3f3f3f'
COLOR_WIRE_FRAME_TABLE = '#3f3f3f'

DATA_DS_IRP = "DSIRP"

DIMENSION_PLANE_LENGTH = "plane_length"
DIMENSION_PLANE_RESOLUTION = "plane_resolution"
DIMENSION_PLANE_WIDTH = "plane_width"

DIMENSION_CYLINDER_LENGTH = 'cylinder_length'
DIMENSION_CYLINDER_RADII_A = 'cylinder_radii_a'
DIMENSION_CYLINDER_RADII_B = 'cylinder_radii_b'
DIMENSION_CYLINDER_RESOLUTION = 'cylinder_resolution'

DIMENSION_TABLE_LENGTH = 'table_length'
DIMENSION_TABLE_WIDTH = 'table_width'
DIMENSION_TABLE_THICKNESS = 'table_thickness'

DIMENSION_PAD_LENGTH = 'pad_length'
DIMENSION_PAD_WIDTH = 'pad_width'
DIMENSION_PAD_THICKNESS = 'pad_thickness'

DIMENSION_UNIT = 'unit'
DIMENSION_UNIT_CM = 'cm'


IRRADIATION_EVENT_PROCEDURE_KEY_BEAM = "Beam"
IRRADIATION_EVENT_PROCEDURE_KEY_DETECTORS = "Detectors"
IRRADIATION_EVENT_PROCEDURE_KEY_PAD = "Pad"
IRRADIATION_EVENT_PROCEDURE_KEY_PATIENT = "Patient"
IRRADIATION_EVENT_PROCEDURE_KEY_SOURCE = "Source"
IRRADIATION_EVENT_PROCEDURE_KEY_TABLE = "Table"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_BEAM = "WF Beam"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_DETECTORS = "WF Detectors"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_PAD = "WF Pad"
IRRADIATION_EVENT_PROCEDURE_KEY_WIRE_FRAME_TABLE = "WF Table"
IRRADIATION_EVENT_STEP_KEY_ARGUMENTS = "args"
IRRADIATION_EVENT_STEP_KEY_LABEL = "label"
IRRADIATION_EVENT_STEP_KEY_METHOD = "method"

MAXIMUM_NUMBER_OF_EVENTS_FOR_INCLUDING_PHANTOM_IN_EVENT_PLOT = 200  # Set to avoid memory errors

MESH_NAME_PAD = "Support pad"
MESH_OPACITY_BEAM = 1.0  # Plotly cannot handle opacity less than 1 at the moment

MODE_CALCULATE_DOSE = "calculate_dose"
MODE_PLOT_EVENT = "plot_event"
MODE_PLOT_PROCEDURE = "plot_procedure"
MODE_PLOT_SETUP = "plot_setup"
MODE_PLOT_DOSEMAP = 'plot_dosemap'
MODE_DARK_MODE = "dark_mode"

OUTPUT_KEY_CORRECTION_BACK_SCATTER = "k_bs"
OUTPUT_KEY_CORRECTION_INVERSE_SQUARE_LAW = "k_isq"
OUTPUT_KEY_CORRECTION_MEDIUM = "k_med"
OUTPUT_KEY_CORRECTION_TABLE = "k_tab"
OUTPUT_KEY_DOSE_MAP = "dose_map"
OUTPUT_KEY_HITS = "hits"
OUTPUT_KEY_KERMA = "kerma"

PHANTOM_MESH_ADULT_MALE = "hudfrid"

PHANTOM_MODEL_CYLINDER = "cylinder"
PHANTOM_MODEL_HUMAN = "human"
PHANTOM_MODEL_PAD = "pad"
PHANTOM_MODEL_PLANE = "plane"
PHANTOM_HUMAN_MESH_SPARSE_MODEL_ENDING = "_reduced_1000t"
PHANTOM_MODEL_TABLE = "table"


PLOT_AXIS_TITLE_X = "X - LON [cm]"
PLOT_AXIS_TITLE_Y = "Y - VER [cm]"
PLOT_AXIS_TITLE_Z = "Z - LAT [cm]"

PLOT_FONT_FAMILY = 'Arial'
PLOT_FONT_SIZE = 14

PLOT_HOVERLABEL_FONT_FAMILY = 'Arial'
PLOT_HOVERLABEL_FONT_SIZE= 14

PLOT_TITLE_FONT_FAMILY = 'Arial'
PLOT_TITLE_FONT_SIZE = 14

PLOT_SLIDER_BORDER_WIDTH = 3
PLOT_SLIDER_FONT_SIZE_CURRENT = 18
PLOT_SLIDER_FONT_SIZE_GENERAL = 14
PLOT_SLIDER_PADDING = dict(b=0, t=0, l=250, r=250)
PLOT_WIREFRAME_LINE_WIDTH = 4
PLOT_DRAGMODE = 'orbit'

PLOT_ASPECTMODE_SETUP_AND_EVENT = 'data'
PLOT_ASPECTMODE_PLOT_PROCEDURE= 'cube'

PLOT_PROCEDURE_AXIS_RANGE_X = [-150, 150]
PLOT_PROCEDURE_AXIS_RANGE_Y = [-150, 150]
PLOT_PROCEDURE_AXIS_RANGE_Z = [-150, 150]

PLOT_SOURCE_SIZE = 8

PLOT_LIGHTNING_DIFFUSE = 0.5
PLOT_LIGHTNING_AMBIENT = 0.5

PLOT_SLIDER_TRANSITION = dict(duration=300, easing="quad-in-out")

PLOT_ZERO_LINE_WIDTH = 5

PLOT_HEIGHT_NOTEBOOK = 700
PLOT_MARGIN_NOTEBOOK = dict(l=5, r=5, b=5, t=40)

RESOLUTION_SPARSE = "sparse"

TABULATED_FIELD_SIDE_LENGTHS_IN_CM = [5, 10, 20, 25, 35]

VISUAL_OFFSET_PHANTOM_MODEL_PLANE = -0.01  # Offset needed to show plane phantom correctly
MODE_NOTEBOOK_MODE = 'notebook_mode'